inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

plugins:
  - rubocop-capybara

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Metrics/BlockLength:
  Exclude:
    - 'tasks/*'
    - 'spec/**/*'
    - 'obs_github_deployments.gemspec'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 3
